---
# Our automated harvesting server tests rely on the paging limits to be set to something low (so that the behavior can be triggered and tested without having to create and export 100 datasets)

- name: set page size limit for ListIdentifiers
  shell: '{{ payara_dir}}/bin/asadmin create-jvm-options "-Ddataverse.oai.server.maxidentifiers={{ harvest.oaiserver.maxidentifiers }}"'
  when: harvest.oaiserver.maxidentifiers is defined

- name: set page size limit for ListRecords
  shell: '{{ payara_dir}}/bin/asadmin create-jvm-options "-Ddataverse.oai.server.maxrecords={{ harvest.oaiserver.maxrecords }}"'
  when: harvest.oaiserver.maxrecords is defined

