---
# dataverse/tasks/dataverse-glassfish.yml

- name: install glassfish
  debug:
    msg: '##### GLASSFISH #####'

- name: glassfish_dir must exist
  file: path={{ glassfish_dir }} state=directory
        owner=root group=root mode=0755

- name: bsdtar can unzip in smarter ways
  yum:
    name: bsdtar
    state: latest

- name: download glassfish zip
  get_url:
    url: '{{ dataverse.glassfish.zipurl }}'
    checksum: '{{ dataverse.glassfish.zipchecksum }}'
    dest: /tmp/glassfish.zip
  register: glassfish_zip_download

- name: unzip to glassfish root without name/version tld
  shell: 'bsdtar --strip-components=1 -C {{ glassfish_dir }} -xf /tmp/glassfish.zip'
  when: glassfish_zip_download.changed
  notify: enable and restart glassfish

- name: create glassfish service group
  group: name={{ dataverse.glassfish.group }} state=present

- name: create glassfish service account
  user: name={{ dataverse.glassfish.user }} group={{ dataverse.glassfish.group }}

- name: glassfish service account should own {{ dataverse.glassfish.domain }}
  file: path={{ glassfish_dir }}/glassfish/domains/{{ dataverse.glassfish.domain }} owner={{ dataverse.glassfish.user }}
        group={{ dataverse.glassfish.group }} state=directory recurse=yes

- name: remove old weld jar included with glassfish-4.1
  file:
    name: '{{ glassfish_dir }}/glassfish/modules/weld-osgi-bundle.jar'
    state: absent
  when: dataverse.glassfish.zipurl is match(".*glassfish-4.1.zip")
  notify: enable and restart glassfish

- name: get patched weld jar for glassfish-4.1
  get_url:
    url: 'https://search.maven.org/remotecontent?filepath=org/jboss/weld/weld-osgi-bundle/2.2.10.Final/weld-osgi-bundle-2.2.10.Final-glassfish4.jar'
    dest: '{{ glassfish_dir }}/glassfish/modules'
    owner: root
    group: root
    mode: 0644
  when: dataverse.glassfish.zipurl is match(".*glassfish-4.1.zip")
  notify: enable and restart glassfish

- name: remove old grizzly jar included with glassfish-4.1
  file:
    name: '{{ glassfish_dir }}/glassfish/modules/glassfish-grizzly-extra-all.jar'
    state: absent
  when: dataverse.glassfish.zipurl is match(".*glassfish-4.1.zip")
  notify: enable and restart glassfish

- name: get patched grizzly jar for glassfish-4.1
  get_url:
    url: http://guides.dataverse.org/en/{{ dataverse.version if dataverse_branch == 'release' else 'latest' }}/_static/installation/files/issues/2180/grizzly-patch/glassfish-grizzly-extra-all.jar
    dest: '{{ glassfish_dir }}/glassfish/modules'
    owner: root
    group: root
    mode: 0644
  when: dataverse.glassfish.zipurl is match(".*glassfish-4.1.zip")
  notify: enable and restart glassfish

# python installer fails to place jdbc driver for whatever reason
# and we want this configurable for testing updated drivers anyway
- name: set jdbcurl
  set_fact:
   jdbc_url='{{ db.postgres.jdbcurl }}'

- name: install custom jdbc driver
  get_url:
    url: '{{ db.postgres.jdbcurl }}'
    dest: '{{ glassfish_dir }}/glassfish/lib/'
  when: jdbc_url|default(None)

- name: allow installer write access for release jdbc driver
  file:
    path: '{{ glassfish_dir }}/glassfish/lib'
    state: directory
    owner: '{{ dataverse.glassfish.user }}'
  when: not jdbc_url|default(None)

- name: install release jdbc driver
  copy:
    src: "{{ item }}"
    dest: "{{ glassfish_dir }}/glassfish/lib/"
    remote_src: true
  when: not jdbc_url|default(None)
  notify: enable and restart glassfish
  with_fileglob: /tmp/dvinstall/pgdriver/postgresql-*.jar

- name: increase resource limits for glassfish
  blockinfile:
    path: /etc/security/limits.conf
    block: |
      {{ item.user }} {{ item.type }} {{ item.descriptor }} {{ item.value }}
    marker: '# {mark} ANSIBLE MANAGED BLOCK {{ item.user }} {{ item.type }} {{ item.descriptor }}'
  with_items:
    - { user: "{{ dataverse.glassfish.user }}", type: soft, descriptor: nproc, value: 65000 }
    - { user: "{{ dataverse.glassfish.user }}", type: hard, descriptor: nproc, value: 65000 }
    - { user: "{{ dataverse.glassfish.user }}", type: soft, descriptor: nofile, value: 65000 }
    - { user: "{{ dataverse.glassfish.user }}", type: hard, descriptor: nofile, value: 65000 }
  notify: enable and restart glassfish

- name: install glassfish systemd conf file for RedHat / CentOS7
  template: src=glassfish.service.j2 dest=/usr/lib/systemd/system/glassfish.service
        owner=root group=root mode=0644
  when: ansible_os_family == "RedHat"
  notify: reload systemd

- name: install glassfish systemd conf file for Debian
  template: src=glassfish.service.j2 dest=/etc/systemd/system/glassfish.service
        owner=root group=root mode=0644
  when: ansible_os_family == "Debian"
  notify: reload systemd

- name: agent must be on glassfish classpath
  copy:
    src: '{{ dataverse.jacoco.home }}/lib/jacocoagent.jar'
    dest: '{{ dataverse.glassfish.root }}/{{ dataverse.glassfish.dir }}/glassfish/lib/jacocoagent.jar'
  when: dataverse.jacoco.enabled == true
  notify: enable and restart glassfish

- name: configure jacoco agent
  lineinfile:
    path: '{{ glassfish_dir }}/glassfish/domains/{{ dataverse.glassfish.domain }}/config/domain.xml'
    line: '        <jvm-options>-Djavaagent:{{ dataverse.glassfish.root }}/{{ dataverse.glassfish.dir }}/glassfish/lib/jacocoagent.jar'
    insertafter: 'dataverse.timerServer'
  when: dataverse.jacoco.enabled == true
  notify: enable and restart glassfish

- name: install glassfish upstart script for older Debian/Ubuntu
  template: src=glassfish.conf.j2 dest=/etc/init
        owner=root group=root mode=0644
  when:
   - ansible_os_family == "Debian"
   - ansible_distribution_major_version < 9
  notify: enable and restart glassfish

- name: flush hadlers to start glassfish and possibly reload systemd
  meta: flush_handlers
