---

- name: get initial admin API token
  postgresql_query:
    db: '{{ db.postgres.name }}'
    login_user: '{{ db.postgres.user }}'
    login_password: '{{ db.postgres.pass }}'
    query: select tokenstring from apitoken where authenticateduser_id = '1'
  register: query_result

- name: print result
  set_fact:
    queryresult_list: '{{ query_result.query_result }}'

- name: set api_token fact
  set_fact:
    api_token: '{{ item.tokenstring }}'
    cacheable: true
  with_items:
  - '{{ queryresult_list }}'
