---

- name: install postfix
  package:
    name: postfix
    state: latest

- name: place main.cf template
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: '0644'
  when:
  - ansible_os_family == "RedHat"
  - ansible_distribution_major_version == "8"

- name: enable and start postfix
  systemd:
    name: postfix
    enabled: yes
    state: started
