---

- name: we need awscli on 7
  yum:
    name: awscli
    state: latest
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"

- name: we need awscli on 8
  pip:
    name: awscli
    executable: pip3
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "8"

- name: ensure dot dir exists
  file:
    path: '~{{ dataverse.payara.user }}/.aws'
    state: directory
    owner: '{{ dataverse.payara.user }}'
    group: '{{ dataverse.payara.group }}'
    mode: '0700'
    
- name: place aws credentials
  template:
    src: aws_credentials.j2
    dest: '~{{ dataverse.payara.user }}/.aws/credentials'
    owner: '{{ dataverse.payara.user }}'
    group: '{{ dataverse.payara.group }}'
    mode: '0600'

- name: place aws config
  template:
    src: aws_config.j2
    dest: '~{{ dataverse.payara.user }}/.aws/config'
    owner: '{{ dataverse.payara.user }}'
    group: '{{ dataverse.payara.group }}'
    mode: '0600'

- name: set storage-driver-id to s3
  shell: '{{ payara_dir}}/bin/asadmin create-jvm-options "-Ddataverse.files.storage-driver-id={{ s3.storage_driver_id }}"'

- name: set s3 type to s3
  shell: '{{ payara_dir}}/bin/asadmin create-jvm-options "-Ddataverse.files.s3.type={{ s3.files_type }}"'

- name: set s3 label to s3
  shell: '{{ payara_dir}}/bin/asadmin create-jvm-options "-Ddataverse.files.s3.label={{ s3.label }}"'

- name: set s3 bucket name
  shell: '{{ payara_dir}}/bin/asadmin create-jvm-options "-Ddataverse.files.s3.bucket-name={{ s3.bucket_name }}"'

- name: set s3 url expiration minutes
  shell: '{{ payara_dir}}/bin/asadmin create-jvm-options "-Ddataverse.files.s3.url-expiration-minutes={{ s3.url_expiration_minutes }}"'

# optional s3 settings

- name: create S3 bucket
  shell:
    'aws s3api create-bucket --bucket {{ s3.bucket_name }} {{ ("--endpoint-url " + s3.custom_endpoint_url) if s3.custom_endpoint_url is defined else ""}}'
  args:
    executable: /bin/bash
  become_user: '{{ dataverse.payara.user }}'
  environment:
    PATH: "{{ lookup('env', 'PATH') }}:/usr/local/bin"
  when: s3.create_bucket == true

- name: "place s3_cors.json template"
  template:
    src: s3_cors.json.j2
    dest: '~{{ dataverse.payara.user }}/s3_cors.json'
    owner: '{{ dataverse.payara.user }}'
    group: '{{ dataverse.payara.group }}'
    mode: 0644
  when: s3.download_redirect == true or
    s3.upload_redirect == true

- name: enable CORS on S3 bucket
  shell:
    'aws s3api put-bucket-cors --bucket {{ s3.bucket_name }} --cors-configuration file://~{{ dataverse.payara.user }}/s3_cors.json {{ ("--endpoint-url " + s3.custom_endpoint_url) if s3.custom_endpoint_url is defined else ""}}'
  args:
    executable: /bin/bash
  become: yes
  become_user: '{{ dataverse.payara.user }}'
  environment:
    PATH: "{{ lookup('env', 'PATH') }}:/usr/local/bin"
  when: s3.download_redirect == true or
    s3.upload_redirect == true

- name: set s3 direct download
  shell: '{{ payara_dir}}/bin/asadmin create-jvm-options "-Ddataverse.files.s3.download-redirect={{ s3.download_redirect }}"'
  when: s3.download_redirect == true

- name: set s3 direct upload
  shell: '{{ payara_dir}}/bin/asadmin create-jvm-options "-Ddataverse.files.s3.upload-redirect={{ s3.upload_redirect }}"'
  when: s3.upload_redirect == true

- include: s3_custom_endpoint_url.yml
  when: s3.custom_endpoint_url is defined

- name: set s3 path style access
  shell: '{{ payara_dir}}/bin/asadmin create-jvm-options "-Ddataverse.files.s3.path-style-access={{ s3.path_style_access }}"'
  when: s3.path_style_access == true
