---

- name: RHEL8 and RockyLinux don't play nice with postgresql9.6
  set_fact:
    die: "RHEL8/Rocky's python-psycopg2 isn't backwards-compatible with PostgresQL 9.6. Use PostgresQL 10 or higher."
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "8" and
        db.postgres.version < 10

- name: Shibboleth requires AJP
  set_fact:
    die: "Shibboleth requires AJP"
  when: apache.use_ajp == false and
        shibboleth.enabled == true

- name: squawk
  debug:
    msg: '{{ die }}'
  when: die is defined

- name: bail
  meta: end_play
  when: die is defined
