---

- name: download schemaspy
  get_url:
    url: '{{ schemaspy.jarurl }}'
    dest: /tmp/schemaspy.jar

- name: download jdbc driver
  get_url:
    url: 'https://jdbc.postgresql.org/download/postgresql-42.2.19.jar'
    dest: /tmp/postgresql-42.2.19.jar

- name: ensure output dir exists
  file:
    path: '/var/www/html/schemaspy/{{ dataverse_branch }}'
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: schemaspy says it doesn't need graphviz but it does
  package:
    name: graphviz
    state: latest

- name: run schemaspy
  shell:
    cmd: '/usr/bin/java -jar /tmp/schemaspy.jar -t pgsql -host {{ db.postgres.host }} -db {{ db.postgres.name }} -u {{ db.postgres.user }} -p {{ db.postgres.pass }} -s public -dp /tmp/postgresql-42.2.19.jar -o /var/www/html/schemaspy/{{ dataverse_branch }}'
