---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: centos8
    box: "bento/centos-8.2"
    memory: 3072
    cpus: 2
    interfaces:
      - network_name: forwarded_port
        guest: 80
        host: 8080
  - name: centos7
    box: "bento/centos-7.8"
    memory: 3072
    cpus: 2
    interfaces:
      - network_name: forwarded_port
        guest: 80
        host: 8081
# TODO: Fix error during installation on Ubuntu
#  - name: unbuntu-16.04
#    box: "bento/ubuntu-16.04"
#    memory: 3072
#    cpus: 2
#    interfaces:
#      - network_name: forwarded_port
#        guest: 80
#        host: 8082
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
  config_options:
    defaults:
      remote_tmp: '/tmp'
      # TODO: find alternative approach to 'merge', which is now deprecated
      hash_behaviour: 'merge'
    ssh_connection:
      pipelining: True
      control_path: '/tmp/ansible-ssh-%%h-%%p-%%r'
  inventory:
    group_vars:
      all:
        rserve:
          install: false
          host: localhost
          user: rserve
          group: rserve
          pass: rserve
          port: 6311
          workdir: /tmp/Rserv
    host_vars:
      centos8:
        shibboleth:
          repo: 'http://download.opensuse.org/repositories/security:/shibboleth/CentOS_8/security:shibboleth.repo'
verifier:
  name: ansible
